spring.application.name=storage-spring-boot-starter
storage.type=tencent
storage.oss.bucket-name=ak
storage.oss.access-key=ak
storage.cos.bucket-name=cos-bucket
storage.cos.secret-id=cos-sid
storage.cos.region=cos-region
